import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.cardContainer}>
          <span className={styles.pro}>Available</span>
          <img
            className={styles.round}
            src="https://randomuser.me/api/portraits/women/79.jpg"
            alt="user"
          />
          <h3>Ricky Park</h3>
          <h6>New York</h6>
          <p>
            User interface designer and <br /> front-end developer
          </p>
          <Link href="/bookings">
            <button className={styles.primary}>Book Appointment</button>
          </Link>
          <div className={styles.skills}>
            <h6>Skills</h6>
            <ul>
              <li>UI / UX</li>
              <li>Front End Development</li>
              <li>HTML</li>
              <li>CSS</li>
              <li>JavaScript</li>
              <li>React</li>
              <li>Node</li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
