import type { NextPage } from "next";
import Head from "next/head";
import { IHomeProps } from "Types/home";
import DisplayCard from "Components/displayCard";
import styles from "../styles/Home.module.scss";

const Home: NextPage<IHomeProps> = (props: IHomeProps) => {
  const { doctors } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Appointment Scheduling Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {doctors.map((doc, i) => {
          const href = {
            pathname: "/bookings",
            query: { name: doc.name },
          };
          return <DisplayCard key={i} doctor={doc} href={href} />;
        })}
      </main>
    </div>
  );
};

// This function gets called at build time
export async function getStaticProps() {
  // Call an external API endpoint to get posts
  const res = await fetch("http://localhost:3000/api/doctors");
  const doctors = await res.json();

  return {
    props: {
      doctors,
    },
  };
}

export default Home;
